---
- include_tasks: fix-name-resolution.yml
- name: Include register host tasks
  ansible.builtin.include_tasks:
    file: register-host.yml
  loop: "{{ rh1_lab19_satellite_init_hosts }}"
  loop_control:
    loop_var: _hostname_
