- name: Become block
  become: true
  block:
    # - name: Remove katello-ca-consumer RPM
    #   ansible.builtin.package:
    #     name: "{{ katello-ca-consumer }}"
    #     state: absent
    #   delegate_to: "{{ _hostname_ }}"

    # - name: Remove old registration
    #   ansible.builtin.shell: >-
    #     subscription-manager clean
    #   delegate_to: "{{ _hostname_ }}"

  #Install katello-ca-consumer RPM
    - name: Install katello-ca-consumer RPM
      ansible.builtin.shell: >-
        dnf install
        http://satellite.{{ lb1152_satellite_node_config_internal }}/pub/katello-ca-consumer-latest.noarch.rpm
        -y
      delegate_to: "{{ _hostname_ }}"

  #Purge old Katello fact from Old Satellite
    # - name: Purge RHSM Katello facts
    #   ansible.builtin.shell: >-
    #     sudo rm /etc/rhsm/facts/katello* -f
    #   delegate_to: "{{ _hostname_ }}"

  #Register Node to the Satellite server to use AK_RHEL9 activationkey
    - name: Register Nodes to Satellite
      ansible.builtin.shell: >-
        subscription-manager register
        --org "{{ lb1152_satellite_node_config_org }}"
        --activationkey "{{ lb1152_satellite_node_config_activation_key }}"
      delegate_to: "{{ _hostname_ }}"

 #Enable RHSM manage repos
    # - name: RHSM config manage_repos enabled
    #   ansible.builtin.shell: >-
    #     subscription-manager config --rhsm.manage_repos 1
    #   delegate_to: "{{ _hostname_ }}"

  #Enable the BaseOS, Appstream, and Satellite-Client repos
    # - name: Enable BaseOS, Appstream, Satellite-Client repos on Nodes
    #   ansible.builtin.shell: >-
    #     subscription-manager repos
    #     --enable rhel-9-for-x86_64-appstream-rpms
    #     --enable rhel-9-for-x86_64-baseos-rpms
    #     --enable satellite-client-6-for-rhel-9-x86_64-rpms
    #   delegate_to: "{{ _hostname_ }}"
